/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3e6bb24c-b769-483e-89ca-2e71a738fa14",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5THxhFepD",
    "aws_user_pools_web_client_id": "1qaku8tq7jl5rredc00bi6ni1f",
    "oauth": {}
};


export default awsmobile;
